# External data files for Be Star Bayesian analysis

This folder contains (or expects) some data files that are generated by
the notebooks in this project but are **not** stored directly in the
GitHub repository because of their size. Instead, they are shared through
Google Drive.

Below we explain where each file comes from and how to download it.

---

## 1. `observables_OldBeAtlas.inp`

The file **`observables_OldBeAtlas.inp`** is generated by the notebook:

- `Notebooks/observables_OldBeAtlas.ipynb`

Because this file is large, it is not stored directly in the repository.
You can download it from Google Drive:

- **Download link (observables_OldBeAtlas.inp)**  
  https://drive.google.com/file/d/1q6AU1wuqzdg86MJNMiBEIdSJRq42YPAO/view?usp=drive_link

---

## 2. `emcee` samples from `analysis_BeAtlas.ipynb`

When you run the notebook:

- `Notebooks/analysis_BeAtlas.ipynb`

it produces MCMC samples using **emcee**. The full set of samples from
these runs is stored in a Google Drive folder:

- **Folder link (all emcee samples)**  
  https://drive.google.com/drive/folders/1CbQZfRSi8n08sRJfWXUymBhXyLfxEF9c?usp=drive_link


---

If you have questions about these files or how to use them, please refer
to the main project `README.md` or contact the repository maintainer.
